modLoader="javafml" 
loaderVersion="[40,)"
license="All rights reserved"

[[mods]] 
modId="data_villagers"
version="${file.jarVersion}" 
 
displayName="Data Villagers"
credits="jaredlll08 & Darkhax for the Multiloader Template"
authors="possible_triangle"
description='''
'''

[[dependencies.data_villagers]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.data_villagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
